language: node_js
sudo: false
node_js:
- '6.11.2'

script: npm run test:single

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

dist: trusty