language: node_js
sudo: false
node_js:
- '6.11.2'

script: npm run test:single`

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov


dist: trusty